version: 0.2

#env:
#  variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
       - apt install awscli
      # - command
    #finally:
      # - command
      # - command
  pre_build:
    commands:
       - $(aws ecr get-login --region us-east-1)
      # - command
    #finally:
      # - command
      # - command
  build:
    commands:
       - docker build -t testjavaapp .
       - docker tag testjavaapp:javaapp 151907672846.dkr.ecr.us-east-1.amazonaws.com/test-ecs-repo:javaapp
    #finally:
      # - command
      # - command
  post_build:
    commands:
       - docker push 151907672846.dkr.ecr.us-east-1.amazonaws.com/test-ecs-repo:javaapp
      # - command
    #finally:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
    # - name
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - path
    # - path
