version: 0.2

#env:
#  variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
        #  install:
        #     commands:
            #       - apt install awscli -y
         #       - apt install docker.io -y
         #       - systemctl start docker
    #finally:
      # - command
      # - command
  pre_build:
    commands:
       - $(aws ecr get-login --no-include-email --region us-east-1)
       - REPOSITORY_URI=151907672846.dkr.ecr.us-east-1.amazonaws.com/test-ecs-repo
       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
       - IMAGE_TAG=${COMMIT_HASH:=javaapp}
      # - command
    #finally:
      # - command
      # - command
  build:
    commands:
       - docker build -t $REPOSITORY_URI:latest .
       - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
    #finally:
      # - command
      # - command
  post_build:
    commands:
       - docker push $REPOSITORY_URI:$IMAGE_TAG
       - printf '[{"name":"hello-world","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
    #finally:
      # - command
      # - command
artifacts:
    files: imagedefinitions.json
    # - location
    # - location
    # - name
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - path
    # - path
